[package]
name = "speedruncom-rust"
version = "0.1.0"
authors = ["Cristobal Hall-Ramnos <crishallramos@yahoo.com>"]

[dependencies]
hyper = "0.10.12"
url = "1.4.1"
chrono = "0.3.1"
serde_json = "1.0.2"
serde = "1.0.8"
